### ISSUE TITLE
Status error

### ISSUE THREAD

**Issue by iauglov** [iotaledger/rpchub#221]
The hub does not return the status if the user is not in the database or user already created.

```
python examples/create_user.py 
Traceback (most recent call last):
  File "examples/create_user.py", line 9, in <module>
    stub.CreateUser(messages_pb2.CreateUserRequest(userId='user-1'))
  File "/home/ilya/hdd/nodes/rpchub-test/env/lib/python3.6/site-packages/grpc/_channel.py", line 532, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ilya/hdd/nodes/rpchub-test/env/lib/python3.6/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.FAILED_PRECONDITION
        details = ""
        debug_error_string = "{"created":"@1543569592.101045860","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1099,"grpc_message":"","grpc_status":9}"
>
```

**Comment by th0br0** [comment]
Hey @iauglov , the Hub uses the trailing_metadata field for encoding the actual error. The python lib doesn't support it nicely at the moment, have a look at the script below!

```python
#!/usr/bin/env python

from random import random
import grpc
import proto.messages_pb2 as messages
import proto.hub_pb2_grpc as hub

channel = grpc.insecure_channel('localhost:50051')
stub = hub.HubStub(channel)

req = messages.CreateUserRequest(userId='teaparty %s' % random())
res = stub.CreateUser(req)
print(res)

try:
    res = stub.CreateUser(req)
except grpc.RpcError as e:
    print(e.code().name)
    err = messages.Error.FromString(e.trailing_metadata()[0].value)
    print('server reported: ', err)
```

**Comment by iauglov** [comment]
Ok, i try it, thanks
